module Viperaptor
  require 'viperaptor/constants/constants.rb'
  require 'viperaptor/constants/rambafile_constants.rb'
  require 'viperaptor/constants/rambaspec_constants.rb'
  require 'viperaptor/cli/cli.rb'
  require 'viperaptor/code_generation/code_module.rb'
  require 'viperaptor/code_generation/module_template.rb'
  require 'viperaptor/code_generation/content_generator.rb'
  require 'viperaptor/code_generation/rambafile_generator.rb'
  require 'viperaptor/module_generator.rb'
  require 'viperaptor/template/processor/template_processor.rb'
  require 'viperaptor/template/installer/template_installer_factory'
  require 'viperaptor/configuration/user_preferences.rb'
  require 'viperaptor/template/creator/template_creator.rb'
  require 'viperaptor/tools/string-colorize.rb'
end